### ISSUE TITLE
Use Dashicons instead of importing FontAwesome

### ISSUE THREAD

**Issue by raamdev** [websharks/alert-box-shortcode#1]
Right now ABS [imports FontAwesome](https://github.com/websharks/alert-box-shortcode/blob/3c3f8d27ec342ba3ee328bced1ec0f81002664bd/alert-box-shortcode.php#L70). However, we should use the [WordPress Dashicons](https://developer.wordpress.org/resource/dashicons/) instead of importing FontAwesome; WordPress already includes a lot of icons so there's no need to load a whole new set if we can use the existing ones.

_Forked from https://github.com/websharks/team/issues/59#issuecomment-213952543._

**Comment by kristineds** [comment]
Next Release Changelog:
- **Enhancement**: The Alert Box Shortcode now uses WordPress Dashicons. Props @raamdev and @kristineds. See [Issue #1](https://github.com/websharks/alert-box-shortcode/issues/1).

**Comment by raamdev** [comment]
@kristineds Cool! Since you followed the proper format, that changelog entry was automatically inserted to the release here: https://github.com/websharks/alert-box-shortcode/releases

We have a script watching GitHub comments that start with "Next Release Changelog" and that script then automatically appends the changelog entry to the release with the title "Next Release". :-)

**Comment by kristineds** [comment]
> We have a script watching GitHub comments that start with "Next Release Changelog" and that script then automatically appends the changelog entry to the release with the title "Next Release". :-)

Very nice! I didn't know that. I'll try to remember that on the next GHI I'm going to work on for this project. 😉
