### ISSUE TITLE
000000-dev → dev

### ISSUE THREAD

**Issue by raamdev** [websharks/alert-box-shortcode#7]
We need to rename the `000000-dev` branch to `dev` as outlined in https://github.com/websharks/phings/issues/124. However, we need to wait until we have no [open Pull Requests](https://github.com/websharks/alert-box-shortcode/pulls) in this repo, as those will get deleted when the renaming occurs.

**Comment by kristineds** [comment]
@raamdev I went ahead and renamed the `000000-dev` to `dev` per @jaswsinc's instructions here. https://github.com/websharks/alert-box-shortcode/pull/6#issuecomment-242684226

**Comment by raamdev** [comment]
@kristineds Awesome. Thanks!
